export enum TinkoffAcquiringStatuses {
  NEW = 'NEW',
  FORMSHOWED = 'FORMSHOWED',
  CANCELED = 'CANCELED',
  DEADLINE_EXPIRED = 'DEADLINE_EXPIRED',

  PREAUTHORIZING = 'PREAUTHORIZING',
  AUTHORIZING = 'AUTHORIZING',
  AUTHORIZED = 'AUTHORIZED',
  AUTH_FAIL = 'AUTH_FAIL',
  REJECTED = 'REJECTED',

  TDS_CHECKING = '3DS_CHECKING',
  TDS_CHECKED = '3DS_CHECKED',

  REVERSING = 'REVERSING',
  REVERSED = 'REVERSED',

  CONFIRMING = 'CONFIRMING',
  CONFIRMED = 'CONFIRMED',

  REFUNDING = 'REFUNDING',
  PARTIAL_REFUNDED = 'PARTIAL_REFUNDED',
  REFUNDED = 'REFUNDED',
}
